backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'news'
    label: 'News'
    folder: 'assets/content/news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    format: 'json'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Main Image', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'committee'
    label: 'Committee'
    folder: 'assets/content/committee'
    create: true
    slug: '{{slug}}'
    format: 'json'
    identifier_field: 'name'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Photo', name: 'photo', widget: 'image' }

  - name: 'membership'
    label: 'Membership Fees'
    folder: 'assets/content/membership'
    create: true
    slug: '{{slug}}'
    format: 'json'
    identifier_field: 'type'
    editor:
      preview: false
    fields:
      - { label: 'Membership Type', name: 'type', widget: 'string' }
      - { label: 'Annual Price', name: 'price_year', widget: 'number' }
      - { label: 'Half Year Price', name: 'price_half', widget: 'number' }

  - name: "handbook_pdf"
    label: "Club Handbook"
    widget: "file"
    default: "assets/content/handbook.pdf"
    media_library:
      config:
        multiple: true

  - name: "sailing_instructions_pdf"
    label: "Sailing Instructions"
    widget: "file"
    default: "assets/content/sailing_instructions.pdf"
    media_library:
      config:
        multiple: true